import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
																		 children,
																	 }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body className={`${geistSans.variable} ${geistMono.variable}`}>
		{children}
		<Script strategy={"beforeInteractive"} src="https://kinobox.tv/kinobox.min.js"/>
		</body>
		{/*<Script strategy={"beforeInteractive"} dangerouslySetInnerHTML={{*/}
		{/*	__html: `kbox('.kinobox_player', {search: {query: 'ID_ИЛИ_НАЗВАНИЕ'}})`*/}
		{/*}}></Script>*/}
		</html>
	);
}
